apiVersion: projectsame.io/v1alpha1
metadata:
    name: DrugAnalysis
    version: 0.0.10
pipeline:
    name: "Drug Analysis Pipeline"
    description: "Analyzing drug interactions"
    package: "drug_analysis.py"
run:
    name: "Drug Analysis Pipeline - Run"
    parameters:
        percent_to_withhold_for_test: 0.3
