apiVersion: projectsame.io/v1alpha1
metadata:
    name: ExternalDataSource
    version: 0.0.4
pipeline:
    name: "Using an Exetrnal Data Source - 2"
    description: "A simple kubeflow execution designed to show using an external data source."
    package: "external_datasource.py"
run:
    name: "Using an External Data Source - 2"
    parameters:
        percent_to_withhold_for_test: 0.2
